version: '3.6'
services:

   cloudtop:
      image: heliumdatastage/renci-guacamole-vnc:use-all-defaults
      container_name: cloudtop
      volumes:
         - ${ORTHANC_DATA_DIR:-./data}:/usr/local/renci/data:ro
      entrypoint: /init
      ports: 
         - 8080:8080

   viewer:
      image: ohif/viewer:latest
      container_name: viewer
      volumes:
#         - ${VIEWER_CONFIG:-./config/viewer.json}:/app/app.json:ro
         - ${VIEWER_CONFIG:-./config/renci.js}:/usr/share/nginx/html/config/default.js
         - ${NGINX_CONFIG:-./config/nginx-with-proxy.conf}:/etc/nginx/conf.d/default.conf

   orthanc:
      image: jodogne/orthanc-plugins:latest
      container_name: orthanc
      volumes:
         - ${ORTHANC_CONFIG:-./config/orthanc.json}:/etc/orthanc/orthanc.json:ro
